import type { TObj } from '@tuber/shared'
import { type JSX, Fragment } from 'react'

/** @deprecated */
function getImportedSvgIcon (
  iconName: string,
  props?: unknown
) {
  void props
  const iconTable: TObj<JSX.Element | null> = {
    'phone_outline': null,
    'call_outline': null,
    'personaddoutlined': null,
    'person_add_outline': null,
    'vpn_key_outline': null,
    'checkcircleoutline': null,
    'check_circle_outline': null,
    'doneoutline': null,
    'done_outline': null,
    'beenhereoutline': null,
    'been_here_outline': null,
    'buildoutlined': null,
    'build_outline': null,
    'donealloutlined': null,
    'done_all_outline': null,
    'doneoutlineoutlined': null,
    'done_outline_outline': null,
    'draftsoutlined': null,
    'drafts_outline': null,
    'highlightoffoutlined': null,
    'highlight_off_outline': null,
    'homeoutlined': null,
    'home_outline': null,
    'houseoutlined': null,
    'house_outline': null,
    'hoteloutlined': null,
    'hotel_outline': null,
    'hourglassemptyoutlined': null,
    'hourglass_empty_outline': null,
    'howtoregoutlined': null,
    'how_to_reg_outline': null,
    'httpsoutlined': null,
    'https_outline': null,
    'imagesearchoutlined': null,
    'image_search_outline': null,
    'infooutlined': null,
    'info_outline': null,
    'powersettingsnewoutlined': null,
    'power_settings_new_outline': null,
    'querybuilderoutlined': null,
    'query_builder_outline': null,
    'removecircleoutlineoutlined': null,
    'remove_circle_outline_outline': null,
    'removeredeyeoutlined': null,
    'remove_red_eye_outline': null,
    'reportoutlined': null,
    'report_outline': null,
    'reportproblemoutlined': null,
    'report_problem_outline': null,
    'searchoutlined': null,
    'search_outline': null,
    'settingsoutlined': null,
    'settings_outline': null,
    'menu': null,
    'assignmentoutlined': null,
    'assignment_outline': null,
    'playlistaddoutlined': null,
    'playlist_add_outline': null,
    'subscriptionsoutlined': null,
    'subscriptions_outline': null,
    'addtoqueue': null,
    'add_to_queue': null,
    'Alternateemailoutlined': null,
    'alternate_email_outline': null,
    'postaddoutlined': null,
    'post_add_outline': null,
    'publishoutlined': null,
    'publish_outline': null,
    'arrowforwardiosoutlined': null,
    'arrow_forward_ios_outline': null,
    'monitorOutlined': null,
    'monitor_outline': null,
    'filternoneoutlined': null,
    'filter_none_outline': null,
    'insertphotooutlined': null,
    'insert_photo_outline': null,
    'darkmodeoutlined': null,
    'dark_mode_outline': null,
    'lightmodeoutlined': null,
    'light_mode_outline': null,
    'clearoutlined': null,
    'clear_outline': null,
    'publicoutlined': null,
    'public_outline': null,
    'travelexploreoutlined': null,
    'travel_explore_outline': null,
    'filterlistoutlined': null,
    'filter_list_outline': null,
    'none': <Fragment />
  }
  return iconTable[iconName] ?? null
}

const ImportedSvgIcon = ({
  iconName,
  props
}: {iconName:string;props?:unknown}) => {
  return <>{ getImportedSvgIcon(iconName, props) }</>
}

export default ImportedSvgIcon